### PR TITLE
Taner and Ali: restructured project tree.

### LINKED ISSUE #85: Repo reconfiguration
We shall put 2018fall under its own folder so that annotation service can live along with it. I'd like to be able to commit sooner than later.

### PR DESCRIPTION
**Pull request by taneresme**
Annotation effort now lives in its own folder. No changes in the code;
except for various pom.xml files.

closes #85

### CODE REVIEW

**Comment by vedatakses** [comment]
What the fuck!

**Comment by alidursen** [comment]
vedat what's the problem? 😆

**Comment by vedatakses** [comment]
It’s a huge change bros, looks good anyway! 😄

**Comment by vedatakses** [comment]
- Please remove root src folder
- Please run 'mvn clean' that we can avoid having /target 
- Please add the following line at .gitignore `*/target/**`

**Review by vedatakses — APPROVED** [review]
Looks good 👍

**Pull request merged**
